---
- name: installing apache webserver
  hosts: web
  become_method: sudo
  become: yes
  tasks:
    - name: install apache webserver
      yum:
        name: httpd
        state: present
    - name: copy index.html on default docroot apache (/var/www/html)
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
    - name: start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes


